### ISSUE TITLE
comments don't render

### ISSUE THREAD

**Issue by gabrielsroka** [jasontheone111/Hacker-News-Redesign#1]
![image](https://github.com/jasontheone111/Hacker-News-Redesign/assets/14354736/c9bb2ed2-ef05-452d-a4e6-0aeadbe41a83)

**Comment by NebulaStellaNova** [comment]
Problem Fixed!

**Comment by gabrielsroka** [comment]
kewl. ty. it works now. 

how the heck did it work for you before you took out `curResersive`?
